'packages:builders':
  - packages/builders/*
  - packages/builders/**/*

'packages:collection':
  - packages/collection/*
  - packages/collection/**/*

'packages:discord.js':
  - packages/discord.js/*
  - packages/discord.js/**/*

'packages:docgen':
  - packages/docgen/*
  - packages/docgen/**/*

'packages:proxy':
  - packages/proxy/*
  - packages/proxy/**/*

'packages:proxy-container':
  - packages/proxy-container/*
  - packages/proxy-container/**/*

'packages:rest':
  - packages/rest/*
  - packages/rest/**/*

'packages:rpc':
  - packages/rpc/*
  - packages/rpc/**/*

'packages:voice':
  - packages/voice/*
  - packages/voice/**/*

'packages:website':
  - packages/website/*
  - packages/website/**/*

'packages:ws':
  - packages/ws/*
  - packages/ws/**/*
