export enum RPCCommands {
	Dispatch = 'DISPATCH',
	Authorize = 'AUTHORIZE',
	Authenticate = 'AUTHENTICATE',
	GetGuild = 'GET_GUILD',
	GetGuilds = 'GET_GUILDS',
	GetChannel = 'GET_CHANNEL',
	GetChannels = 'GET_CHANNELS',
	Subscribe = 'SUBSCRIBE',
	Unsubscribe = 'UNSUBSCRIBE',
	SetUserVoiceSettings = 'SET_USER_VOICE_SETTINGS',
	SelectVoiceChannel = 'SELECT_VOICE_CHANNEL',
	GetSelectedVoiceChannel = 'GET_SELECTED_VOICE_CHANNEL',
	SelectTextChannel = 'SELECT_TEXT_CHANNEL',
	GetVoiceSettings = 'GET_VOICE_SETTINGS',
	SetVoiceSettings = 'SET_VOICE_SETTINGS',
	SetCertifiedDevices = 'SET_CERTIFIED_DEVICES',
	SetActivity = 'SET_ACTIVITY',
	SendActivityJoinInvite = 'SEND_ACTIVITY_JOIN_INVITE',
	CloseActivityRequest = 'CLOSE_ACTIVITY_REQUEST',
	// undocumented commands
	CreateChannelInvite = 'CREATE_CHANNEL_INVITE',
	GetRelationships = 'GET_RELATIONSHIPS',
	GetUser = 'GET_USER',
	SetUserVoiceSettings2 = 'SET_USER_VOICE_SETTINGS_2',
	SetVoiceSettings2 = 'SET_VOICE_SETTINGS_2',
	CaptureShortcut = 'CAPTURE_SHORTCUT',
	CloseActivityJoinRequest = 'CLOSE_ACTIVITY_JOIN_REQUEST',
	ActivityInviteUser = 'ACTIVITY_INVITE_USER',
	AcceptActivityInvite = 'ACCEPT_ACTIVITY_INVITE',
	InviteBrowser = 'INVITE_BROWSER',
	DeepLink = 'DEEP_LINK',
	ConnectionsCallback = 'CONNECTIONS_CALLBACK',
	BrainTreePopupBridgeCallback = 'BRAINTREE_POPUP_BRIDGE_CALLBACK',
	GiftCodeBrowser = 'GIFT_CODE_BROWSER',
	GuildTemplateBrowser = 'GUILD_TEMPLATE_BROWSER',
	Overlay = 'OVERLAY',
	BrowserHandoff = 'BROWSER_HANDOFF',
	GetImage = 'GET_IMAGE',
	CreateLobby = 'CREATE_LOBBY',
	UpdateLobby = 'UPDATE_LOBBY',
	DeleteLobby = 'DELETE_LOBBY',
	UpdateLobbyMember = 'UPDATE_LOBBY_MEMBER',
	ConnectToLobby = 'CONNECT_TO_LOBBY',
	DisconnectFromLobby = 'DISCONNECT_FROM_LOBBY',
	SendToLobby = 'SEND_TO_LOBBY',
	SearchLobbies = 'SEARCH_LOBBIES',
	ConnectToLobbyVoice = 'CONNECT_TO_LOBBY_VOICE',
	DisconnectFromLobbyVoice = 'DISCONNECT_FROM_LOBBY_VOICE',
	SetOverlayLocked = 'SET_OVERLAY_LOCKED',
	OpenOverlayActivityInvite = 'OPEN_OVERLAY_ACTIVITY_INVITE',
	OpenOverlayGuildInvite = 'OPEN_OVERLAY_GUILD_INVITE',
	OpenOverlayVoiceSettings = 'OPEN_OVERLAY_VOICE_SETTINGS',
	ValidateApplication = 'VALIDATE_APPLICATION',
	GetEntitlementTicket = 'GET_ENTITLEMENT_TICKET',
	GetApplicationTicket = 'GET_APPLICATION_TICKET',
	StartPurchase = 'START_PURCHASE',
	GetSKUS = 'GET_SKUS',
	GetEntitlements = 'GET_ENTITLEMENTS',
	GetNetworkingConfig = 'GET_NETWORKING_CONFIG',
	NetworkingSystemMetrics = 'NETWORKING_SYSTEM_METRICS',
	NetworkingPeerMetrics = 'NETWORKING_PEER_METRICS',
	NetworkingCreateToken = 'NETWORKING_CREATE_TOKEN',
	SetUserAchievement = 'SET_USER_ACHIEVEMENT',
	GetUserAchievements = 'GET_USER_ACHIEVEMENTS',
}

export enum RPCEvents {
	Ready = 'READY',
	Error = 'ERROR',
	GuildStatus = 'GUILD_STATUS',
	GuildCreate = 'GUILD_CREATE',
	ChannelCreate = 'CHANNEL_CREATE',
	VoiceChannelSelect = 'VOICE_CHANNEL_SELECT',
	VoiceStateCreate = 'VOICE_STATE_CREATE',
	VoiceStateUpdate = 'VOICE_STATE_UPDATE',
	VoiceStateDelete = 'VOICE_STATE_DELETE',
	VoiceSettingsUpdate = 'VOICE_SETTINGS_UPDATE',
	VoiceConnectionStatus = 'VOICE_CONNECTION_STATUS',
	SpeakingStart = 'SPEAKING_START',
	SpeakingStop = 'SPEAKING_STOP',
	MessageCreate = 'MESSAGE_CREATE',
	MessageUpdate = 'MESSAGE_UPDATE',
	MessageDelete = 'MESSAGE_DELETE',
	NotificationCreate = 'NOTIFICATION_CREATE',
	ActivityJoin = 'ACTIVITY_JOIN',
	ActivitySpectate = 'ACTIVITY_SPECTATE',
	ActivityJoinRequest = 'ACTIVITY_JOIN_REQUEST',
	// undocumented events
	CurrentUserUpdate = 'CURRENT_USER_UPDATE',
	RelationshipUpdate = 'RELATIONSHIP_UPDATE',
	VoiceSettingsUpdate2 = 'VOICE_SETTINGS_UPDATE_2',
	GameJoin = 'GAME_JOIN',
	GameSpectate = 'GAME_SPECTATE',
	ActivityInvite = 'ACTIVITY_INVITE',
	LobbyDelete = 'LOBBY_DELETE',
	LobbyUpdate = 'LOBBY_UPDATE',
	LobbyMemberConnect = 'LOBBY_MEMBER_CONNECT',
	LobbyMemberDisconnect = 'LOBBY_MEMBER_DISCONNECT',
	LobbyMemberUpdate = 'LOBBY_MEMBER_UPDATE',
	LobbyMessage = 'LOBBY_MESSAGE',
	CaptureShortcutChange = 'CAPTURE_SHORTCUT_CHANGE',
	Overlay = 'OVERLAY',
	OverlayUpdate = 'OVERLAY_UPDATE',
	EntitlementCreate = 'ENTITLEMENT_CREATE',
	EntitlementDelete = 'ENTITLEMENT_DELETE',
	UserAchievementUpdate = 'USER_ACHIEVEMENT_UPDATE',
}

export enum VoiceConnectionStates {
	Disconnected = 'DISCONNECTED',
	AwaitingEndpoint = 'AWAITING_ENDPOINT',
	Authenticating = 'AUTHENTICATING',
	Connecting = 'CONNECTING',
	Connected = 'CONNECTED',
	VoiceDisconnected = 'VOICE_DISCONNECTED',
	VoiceConnecting = 'VOICE_CONNECTING',
	VoiceConnected = 'VOICE_CONNECTED',
	NoRoute = 'NO_ROUTE',
	IceChecking = 'ICE_CHECKING',
}

export enum KeyType {
	KeyboardKey = 'KEYBOARD_KEY',
	MouseButton = 'MOUSE_BUTTON',
	KeyboardModifierKey = 'KEYBOARD_MODIFIER_KEY',
	GamepadButton = 'GAMEPAD_BUTTON',
}

export enum RPCErrorCodes {
	UnknownError = 1000,
	ServiceUnavailable = 1001,
	TransactionAborted = 1002,
	InvalidPayload = 4000,
	InvalidCommand = 4002,
	InvalidGuild = 4003,
	InvalidEvent = 4004,
	InvalidChannel = 4005,
	InvalidClientId = 4007,
	InvalidOrigin = 4008,
	InvalidToken = 4009,
	InvalidUser = 4010,
	InvalidInvite = 4011,
	InvalidActivityJoinRequest = 4012,
	InvalidLobby = 4013,
	InvalidLobbySecret = 4014,
	InvalidEntitlement = 4015,
	InvalidGiftCode = 4016,
	OAuth2Error = 5000,
	SelectChannelTimedOut = 5001,
	GetGuildTimedOut = 5002,
	SelectVoiceForceRequired = 5003,
	CaptureShortcutAlreadyListening = 5004,
	InvalidActivitySecret = 5005,
	NoEligibleActivity = 5006,
	LobbyFull = 5007,
	PurchaseCanceled = 5008,
	PurchaseError = 5009,
	UnauthorizedForAchievement = 5010,
	RateLimited = 5011,
}

export enum RPCCloseEventCodes {
	CloseNormal = 1000,
	CloseUnsupported = 1003,
	CloseAbnormal = 1006,
	InvalidClientId = 4000,
	InvalidOrigin = 4001,
	RateLimited = 4002,
	TokenRevoked = 4003,
	InvalidVersion = 4004,
	InvalidEncoding = 4005,
}

export enum LobbyType {
	Private = 1,
	Public = 2,
}

export enum RelationshipType {
	None = 0,
	Friend = 1,
	Blocked = 2,
	PendingIncoming = 3,
	PendingOutgoing = 4,
	Implicit = 5,
}
