export enum RPCCommands {
	AcceptActivityInvite = 'ACCEPT_ACTIVITY_INVITE',
	ActivityInviteUser = 'ACTIVITY_INVITE_USER',
	Authenticate = 'AUTHENTICATE',
	Authorize = 'AUTHORIZE',
	BrainTreePopupBridgeCallback = 'BRAINTREE_POPUP_BRIDGE_CALLBACK',
	BrowserHandoff = 'BROWSER_HANDOFF',
	CaptureShortcut = 'CAPTURE_SHORTCUT',
	CloseActivityJoinRequest = 'CLOSE_ACTIVITY_JOIN_REQUEST',
	CloseActivityRequest = 'CLOSE_ACTIVITY_REQUEST',
	ConnectToLobby = 'CONNECT_TO_LOBBY',
	ConnectToLobbyVoice = 'CONNECT_TO_LOBBY_VOICE',
	ConnectionsCallback = 'CONNECTIONS_CALLBACK',
	// undocumented commands
	CreateChannelInvite = 'CREATE_CHANNEL_INVITE',
	CreateLobby = 'CREATE_LOBBY',
	DeepLink = 'DEEP_LINK',
	DeleteLobby = 'DELETE_LOBBY',
	DisconnectFromLobby = 'DISCONNECT_FROM_LOBBY',
	DisconnectFromLobbyVoice = 'DISCONNECT_FROM_LOBBY_VOICE',
	Dispatch = 'DISPATCH',
	GetApplicationTicket = 'GET_APPLICATION_TICKET',
	GetChannel = 'GET_CHANNEL',
	GetChannels = 'GET_CHANNELS',
	GetEntitlementTicket = 'GET_ENTITLEMENT_TICKET',
	GetEntitlements = 'GET_ENTITLEMENTS',
	GetGuild = 'GET_GUILD',
	GetGuilds = 'GET_GUILDS',
	GetImage = 'GET_IMAGE',
	GetNetworkingConfig = 'GET_NETWORKING_CONFIG',
	GetRelationships = 'GET_RELATIONSHIPS',
	GetSKUS = 'GET_SKUS',
	GetSelectedVoiceChannel = 'GET_SELECTED_VOICE_CHANNEL',
	GetUser = 'GET_USER',
	GetUserAchievements = 'GET_USER_ACHIEVEMENTS',
	GetVoiceSettings = 'GET_VOICE_SETTINGS',
	GiftCodeBrowser = 'GIFT_CODE_BROWSER',
	GuildTemplateBrowser = 'GUILD_TEMPLATE_BROWSER',
	InviteBrowser = 'INVITE_BROWSER',
	NetworkingCreateToken = 'NETWORKING_CREATE_TOKEN',
	NetworkingPeerMetrics = 'NETWORKING_PEER_METRICS',
	NetworkingSystemMetrics = 'NETWORKING_SYSTEM_METRICS',
	OpenOverlayActivityInvite = 'OPEN_OVERLAY_ACTIVITY_INVITE',
	OpenOverlayGuildInvite = 'OPEN_OVERLAY_GUILD_INVITE',
	OpenOverlayVoiceSettings = 'OPEN_OVERLAY_VOICE_SETTINGS',
	Overlay = 'OVERLAY',
	SearchLobbies = 'SEARCH_LOBBIES',
	SelectTextChannel = 'SELECT_TEXT_CHANNEL',
	SelectVoiceChannel = 'SELECT_VOICE_CHANNEL',
	SendActivityJoinInvite = 'SEND_ACTIVITY_JOIN_INVITE',
	SendToLobby = 'SEND_TO_LOBBY',
	SetActivity = 'SET_ACTIVITY',
	SetCertifiedDevices = 'SET_CERTIFIED_DEVICES',
	SetOverlayLocked = 'SET_OVERLAY_LOCKED',
	SetUserAchievement = 'SET_USER_ACHIEVEMENT',
	SetUserVoiceSettings = 'SET_USER_VOICE_SETTINGS',
	SetUserVoiceSettings2 = 'SET_USER_VOICE_SETTINGS_2',
	SetVoiceSettings = 'SET_VOICE_SETTINGS',
	SetVoiceSettings2 = 'SET_VOICE_SETTINGS_2',
	StartPurchase = 'START_PURCHASE',
	Subscribe = 'SUBSCRIBE',
	Unsubscribe = 'UNSUBSCRIBE',
	UpdateLobby = 'UPDATE_LOBBY',
	UpdateLobbyMember = 'UPDATE_LOBBY_MEMBER',
	ValidateApplication = 'VALIDATE_APPLICATION',
}

export enum RPCEvents {
	ActivityInvite = 'ACTIVITY_INVITE',
	ActivityJoin = 'ACTIVITY_JOIN',
	ActivityJoinRequest = 'ACTIVITY_JOIN_REQUEST',
	ActivitySpectate = 'ACTIVITY_SPECTATE',
	CaptureShortcutChange = 'CAPTURE_SHORTCUT_CHANGE',
	ChannelCreate = 'CHANNEL_CREATE',
	// undocumented events
	CurrentUserUpdate = 'CURRENT_USER_UPDATE',
	EntitlementCreate = 'ENTITLEMENT_CREATE',
	EntitlementDelete = 'ENTITLEMENT_DELETE',
	Error = 'ERROR',
	GameJoin = 'GAME_JOIN',
	GameSpectate = 'GAME_SPECTATE',
	GuildCreate = 'GUILD_CREATE',
	GuildStatus = 'GUILD_STATUS',
	LobbyDelete = 'LOBBY_DELETE',
	LobbyMemberConnect = 'LOBBY_MEMBER_CONNECT',
	LobbyMemberDisconnect = 'LOBBY_MEMBER_DISCONNECT',
	LobbyMemberUpdate = 'LOBBY_MEMBER_UPDATE',
	LobbyMessage = 'LOBBY_MESSAGE',
	LobbyUpdate = 'LOBBY_UPDATE',
	MessageCreate = 'MESSAGE_CREATE',
	MessageDelete = 'MESSAGE_DELETE',
	MessageUpdate = 'MESSAGE_UPDATE',
	NotificationCreate = 'NOTIFICATION_CREATE',
	Overlay = 'OVERLAY',
	OverlayUpdate = 'OVERLAY_UPDATE',
	Ready = 'READY',
	RelationshipUpdate = 'RELATIONSHIP_UPDATE',
	SpeakingStart = 'SPEAKING_START',
	SpeakingStop = 'SPEAKING_STOP',
	UserAchievementUpdate = 'USER_ACHIEVEMENT_UPDATE',
	VoiceChannelEffectToggleAnimationType = 'VOICE_CHANNEL_EFFECT_TOGGLE_ANIMATION_TYPE',
	VoiceChannelSelect = 'VOICE_CHANNEL_SELECT',
	VoiceConnectionStatus = 'VOICE_CONNECTION_STATUS',
	VoiceSettingsUpdate = 'VOICE_SETTINGS_UPDATE',
	VoiceSettingsUpdate2 = 'VOICE_SETTINGS_UPDATE_2',
	VoiceStateCreate = 'VOICE_STATE_CREATE',
	VoiceStateDelete = 'VOICE_STATE_DELETE',
	VoiceStateUpdate = 'VOICE_STATE_UPDATE',
	ThermalStateUpdate = 'THERMAL_STATE_UPDATE',
}

export enum VoiceConnectionStates {
	Authenticating = 'AUTHENTICATING',
	AwaitingEndpoint = 'AWAITING_ENDPOINT',
	Connected = 'CONNECTED',
	Connecting = 'CONNECTING',
	Disconnected = 'DISCONNECTED',
	IceChecking = 'ICE_CHECKING',
	NoRoute = 'NO_ROUTE',
	VoiceConnected = 'VOICE_CONNECTED',
	VoiceConnecting = 'VOICE_CONNECTING',
	VoiceDisconnected = 'VOICE_DISCONNECTED',
}

export enum VoiceSettingsType {
	PushToTalk = 'PUSH_TO_TALK',
	VoiceActivity = 'VOICE_ACTIVITY',
}

export enum KeyType {
	GamepadButton = 'GAMEPAD_BUTTON',
	KeyboardKey = 'KEYBOARD_KEY',
	KeyboardModifierKey = 'KEYBOARD_MODIFIER_KEY',
	MouseButton = 'MOUSE_BUTTON',
}

export enum PromptType {
	Consent = 'consent',
	None = 'none',
}

export enum RPCErrorCodes {
	UnknownError = 1_000,
	ServiceUnavailable = 1_001,
	TransactionAborted = 1_002,
	InvalidPayload = 4_000,
	InvalidCommand = 4_002,
	InvalidGuild = 4_003,
	InvalidEvent = 4_004,
	InvalidChannel = 4_005,
	InvalidClientId = 4_007,
	InvalidOrigin = 4_008,
	InvalidToken = 4_009,
	InvalidUser = 4_010,
	InvalidInvite = 4_011,
	InvalidActivityJoinRequest = 4_012,
	InvalidLobby = 4_013,
	InvalidLobbySecret = 4_014,
	InvalidEntitlement = 4_015,
	InvalidGiftCode = 4_016,
	OAuth2Error = 5_000,
	SelectChannelTimedOut = 5_001,
	GetGuildTimedOut = 5_002,
	SelectVoiceForceRequired = 5_003,
	CaptureShortcutAlreadyListening = 5_004,
	InvalidActivitySecret = 5_005,
	NoEligibleActivity = 5_006,
	LobbyFull = 5_007,
	PurchaseCanceled = 5_008,
	PurchaseError = 5_009,
	UnauthorizedForAchievement = 5_010,
	RateLimited = 5_011,
}

export enum RPCCloseEventCodes {
	CloseNormal = 1_000,
	CloseUnsupported = 1_003,
	CloseAbnormal = 1_006,
	InvalidClientId = 4_000,
	InvalidOrigin = 4_001,
	RateLimited = 4_002,
	TokenRevoked = 4_003,
	InvalidVersion = 4_004,
	InvalidEncoding = 4_005,
}

export enum LobbyType {
	Private = 1,
	Public = 2,
}

export enum RelationshipType {
	None = 0,
	Friend = 1,
	Blocked = 2,
	PendingIncoming = 3,
	PendingOutgoing = 4,
	Implicit = 5,
}
